### ISSUE TITLE
Create IAM User Scripts

### ISSUE THREAD

**Issue by bellanov** [bellanov/aws-bootstrap#1]
Establish scripts to _create_, _modify_, and _delete_ **IAM Users**.

**Resources**

_Creating an IAM User_
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/create-user.html

_Creating an Access / Secret Key_
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/create-access-key.html

_Attach IAM Policy to User_
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/attach-user-policy.html

**Tasks**

- Create a script to _create_ a service account and attach a policy
- Create a script to _modify_ a service account by simply replacing its policy
- Create a script to _delete_ a service account
- Create a script to generate _Secret_ and _Access Keys_

**Comment by bellanov** [comment]
I'll post an update here once I create the **Administrators** group and add us to it. The permissions should pretty much match the terraform identity that currently exists.

**Comment by prattsvee** [comment]
**I had a question where do you want a logging system for this entire workflow locally** , AWS will have its own set of logs but just incase . I have come up with some basic scripts which I am yet to test  after I get the admin access I will test and create a PR .

**Comment by bellanov** [comment]
Meh, no need to worry about that. Just ensure the scripts deliver a straightforward, repeatable workflow.

So long as it resembles it's sister project, we're good. We'll be improving these scripts for sure as we go.
https://github.com/bellanov/gcp-bootstrap?tab=readme-ov-file#examples

We'll discuss log aggregation in another issue. I'll likely have -Puter continuously scan environments and generate KPIs, so it may just need to tail the AWS CloudTrail logs or whatever.

**Comment by prattsvee** [comment]
Raised an PR for this task , please review and let me know the changes required . @bellanov

**Comment by bellanov** [comment]
Great. I'll take a look when I get a chance.
